---
title: "01__raw_norm_gsk3i__1"
output: html_document
---


Background

Here I process columns, filter, and normalise


###Initialise

Packages
```{r}
library(reshape2)
```


###Read in data
```{r}
phos_gsk3i_raw <- read.delim("data/raw/3T3L1_Gsk3i__phos__XD__20210531.txt",
                           sep = "\t",
                           header = TRUE)[-1, ]

###Make intensity columns numeric
intensity_col_indices <- grep("Intensity.",
                      colnames(phos_gsk3i_raw))
for (j in 1:length(intensity_col_indices)){
  
  phos_gsk3i_raw[, intensity_col_indices[j]] <- as.numeric(phos_gsk3i_raw[, intensity_col_indices[j]])
}
```

###Process columns and add rownames
```{r}
###Uniprot
phos_gsk3i_raw$uniprot <- phos_gsk3i_raw$Protein

###Site
#Pick the site that matches the protein
for (i in 1:nrow(phos_gsk3i_raw)){
  
  uniprots <- strsplit(phos_gsk3i_raw$Proteins[i],
                    ";")[[1]]
  
  sites <- strsplit(phos_gsk3i_raw$Positions.within.proteins[i],
                 ";")[[1]]
  
  chosen_uniprot_index <- which(uniprots == phos_gsk3i_raw$Protein[i])
  chosen_site <- sites[chosen_uniprot_index]
  
  phos_gsk3i_raw$site[i] <- gsub(" ",
                                 "",
                                 paste(phos_gsk3i_raw$Amino.acid[i],
                                  chosen_site,
                                  collapse = ""))
  
}

###Gene
#Just take first one
phos_gsk3i_raw$gene <- sapply(phos_gsk3i_raw$Gene.names,
                              function(x) strsplit(x, ";")[[1]][1])

###Standard name
phos_gsk3i_raw$standard_name <- apply(phos_gsk3i_raw[, c("gene",
                                                         "uniprot",
                                                         "site",
                                                         "Multiplicity")],
                                      1,
                                      function(x){
                                        
                                        x_paste <- paste(x,
                                                         collapse = ";")
                                        x_paste_strip <- gsub("_",
                                                              "",
                                                              x_paste)
                                        return(gsub(";",
                                                    "_",
                                                    x_paste_strip))
                                      })

###uniprot_site
phos_gsk3i_raw$uniprot_site <- sapply(phos_gsk3i_raw$standard_name,
                                      function(x) paste(strsplit(x, 
                                                                 "_")[[1]][2:3],
                                                        collapse = "_"))

#Assess NA
#112 NAs genes
#No NA uniprots
length(which(is.na(phos_gsk3i_raw$gene)))
length(which(is.na(phos_gsk3i_raw$uniprot)))
length(which(is.na(phos_gsk3i_raw$standard_name)))
length(which(is.na(phos_gsk3i_raw$uniprot_site)))


###Rename intensity
colnames(phos_gsk3i_raw) <- gsub("Intensity.",
                                 "",
                                 colnames(phos_gsk3i_raw))

###Rownames
rownames(phos_gsk3i_raw) <- phos_gsk3i_raw$standard_name
```



###BIg numbers
```{r}
##Quantified
#14778 ppeptides
#12295 psites
#3263 pproteins
length(which(rowSums(is.na(phos_gsk3i_raw[, 1:8])) < 8))
length(unique(phos_gsk3i_raw$uniprot_site[which(rowSums(is.na(phos_gsk3i_raw[, 1:8])) < 8)]))
length(unique(phos_gsk3i_raw$uniprot[which(rowSums(is.na(phos_gsk3i_raw[, 1:8])) < 8)]))

##Peptides quantified across all ns
#5639
length(which(rowSums(is.na(phos_gsk3i_raw[, 1:8])) == 0))
```




###Normalisation

```{r}
###Visualise before normalisation:
pdf("output/images/processing/boxplot_before_norm.pdf")
boxplot(phos_gsk3i_raw[, 1:8], las = 2, pch = 20, cex = 0.5)
dev.off()

###Median-normalise:
medians <- apply(phos_gsk3i_raw[, 1:8], 2, FUN = median, na.rm = TRUE)
overall_median <- median(medians)
med_diffs <- medians - overall_median
phos_gsk3i_raw_norm <- phos_gsk3i_raw
phos_gsk3i_raw_norm[, 1:8] <- sweep(phos_gsk3i_raw_norm[, 1:8], 2, med_diffs, FUN = "-")

###Visualise after normalisation:
pdf("output/images/processing/boxplot_after_norm.pdf")
boxplot(phos_gsk3i_raw_norm[, 1:8], las = 2, pch = 20, cex = 0.5)
dev.off()
```
###Remove unnecessary columns
```{r}
phos_gsk3i_raw_norm <- phos_gsk3i_raw_norm[, c("Basal_1",
                                               "Basal_2",
                                               "Basal_3",
                                               "Basal_4",
                                               "GSK3i_1",
                                               "GSK3i_2",
                                               "GSK3i_3",
                                               "GSK3i_4",
                                               "gene",
                                               "uniprot",
                                               "site",
                                               "uniprot_site",
                                               "standard_name",
                                               "Proteins",
                                               "Positions.within.proteins",
                                               "Gene.names",
                                               "Sequence.window")]
```


###Output
```{r}
###phos_gsk3i_raw
#The only actual filtering that has been done is removing the first 32 rows, which did not have gene names
save(phos_gsk3i_raw,
     file = "output/data/phos_gsk3i_raw__1.RData")

###phos_gsk3i_raw_norm
#Above but normalised
#This is what I will take into further analysis
save(phos_gsk3i_raw_norm,
     file = "output/data/phos_gsk3i_raw_norm__1.RData")
```









































