---
title: "05__pot_sub_filtering__6"
output: html_document
---




Background

Here I filter for potential substrates




###Initialise



###Read in data
```{r}
load("data/intermediate/phos_gsk3i_raw_norm_imp_below_ds1_looser_strin2stats__1.RData")

###Psp phosphporylation data
psp_phos_data <- read.delim("data/intermediate/PSP__phos_dataset__20210127")
psp_phos_data_mouse <- psp_phos_data[which(psp_phos_data$ORGANISM == "mouse"), ]
psp_phos_data_mouse$uniprot_site <- apply(psp_phos_data_mouse[, c("ACC_ID",
                                                                  "MOD_RSD")],
                                          1,
                                          function(x) {
                                            
                                            x[2] <- sub("-p",
                                                        "",
                                                        x[2])
                                            return(paste(x,
                                                         collapse = "_"))
                                          })
```

###Motif filtering
```{r}
phos_gsk3i_raw_norm_imp_below_ds1_looser_strin2stats$matches_pST35psp_motif <- FALSE


for (i in 1:nrow(phos_gsk3i_raw_norm_imp_below_ds1_looser_strin2stats)){
  #Process uniprot_site
  uniprot_site <- phos_gsk3i_raw_norm_imp_below_ds1_looser_strin2stats$uniprot_site[i]
  uniprot <- sub("_.+",
                 "",
                 uniprot_site)
  site <- sub(".+_",
              "",
              uniprot_site)
  site_res <- strsplit(site,
                             "")[[1]][1]
  site_num <- as.numeric(paste(strsplit(site,
                                        "")[[1]][-1],
                         collapse = ""))
  
  #Make plus4 uniprot_site
  plus4_site_num <- site_num + 4
  plus4_uniprot_site_ser <- paste(c(uniprot,
                                    "_",
                                    "S",
                                    plus4_site_num),
                                  collapse = "")
  plus4_uniprot_site_thr <- paste(c(uniprot,
                                    "_",
                                    "T",
                                    plus4_site_num),
                                  collapse = "")
  #Make plus3 uniprot_site
  plus3_site_num <- site_num + 3
  plus3_uniprot_site_ser <- paste(c(uniprot,
                                    "_",
                                    "S",
                                    plus3_site_num),
                                  collapse = "")
  plus3_uniprot_site_thr <- paste(c(uniprot,
                                    "_",
                                    "T",
                                    plus3_site_num),
                                  collapse = "")
  #Make plus5 uniprot_site
  plus5_site_num <- site_num + 5
  plus5_uniprot_site_ser <- paste(c(uniprot,
                                    "_",
                                    "S",
                                    plus5_site_num),
                                  collapse = "")
  plus5_uniprot_site_thr <- paste(c(uniprot,
                                    "_",
                                    "T",
                                    plus5_site_num),
                                  collapse = "")
  
  #pST35psp motif: plus3,4, or 5 uniprot_site identified or in psp, and S/T
  if (site_res %in% c("S",
                      "T") &
      (plus3_uniprot_site_ser %in%
       c(phos_gsk3i_raw_norm_imp_below_ds1_looser_strin2stats$uniprot_site,
         psp_phos_data_mouse$uniprot_site) |
       plus3_uniprot_site_thr %in%
       c(phos_gsk3i_raw_norm_imp_below_ds1_looser_strin2stats$uniprot_site,
         psp_phos_data_mouse$uniprot_site) |
       plus4_uniprot_site_ser %in%
       c(phos_gsk3i_raw_norm_imp_below_ds1_looser_strin2stats$uniprot_site,
         psp_phos_data_mouse$uniprot_site) |
       plus4_uniprot_site_thr %in%
       c(phos_gsk3i_raw_norm_imp_below_ds1_looser_strin2stats$uniprot_site,
         psp_phos_data_mouse$uniprot_site) |
       plus5_uniprot_site_ser %in%
       c(phos_gsk3i_raw_norm_imp_below_ds1_looser_strin2stats$uniprot_site,
         psp_phos_data_mouse$uniprot_site) |
       plus5_uniprot_site_thr %in%
       c(phos_gsk3i_raw_norm_imp_below_ds1_looser_strin2stats$uniprot_site,
         psp_phos_data_mouse$uniprot_site))){
    
    phos_gsk3i_raw_norm_imp_below_ds1_looser_strin2stats$matches_pST35psp_motif[i] <- TRUE
       }
}


###Assess with sites downstream of GSK3i
length(which((phos_gsk3i_raw_norm_imp_below_ds1_looser_strin2stats$GSK3i_up == TRUE) &
               phos_gsk3i_raw_norm_imp_below_ds1_looser_strin2stats$matches_pST4psp_motif == TRUE))
length(which((phos_gsk3i_raw_norm_imp_below_ds1_looser_strin2stats$GSK3i_down == TRUE) &
               phos_gsk3i_raw_norm_imp_below_ds1_looser_strin2stats$matches_pST4psp_motif == TRUE))

length(which((phos_gsk3i_raw_norm_imp_below_ds1_looser_strin2stats$GSK3i_up == TRUE) &
               phos_gsk3i_raw_norm_imp_below_ds1_looser_strin2stats$matches_pST35psp_motif == TRUE))
length(which((phos_gsk3i_raw_norm_imp_below_ds1_looser_strin2stats$GSK3i_down == TRUE) &
               phos_gsk3i_raw_norm_imp_below_ds1_looser_strin2stats$matches_pST35psp_motif == TRUE))
```



##Export matches data
```{r}
phos_gsk3i_raw_norm_imp_below_ds1_looser_strin2stats_potsub <- phos_gsk3i_raw_norm_imp_below_ds1_looser_strin2stats

#Change Tusc5 to Trarg1
phos_gsk3i_raw_norm_imp_below_ds1_looser_strin2stats_potsub$gene <- gsub("Tusc5",
                                                                         "Trarg1",
                                                                         phos_gsk3i_raw_norm_imp_below_ds1_looser_strin2stats_potsub$gene)
phos_gsk3i_raw_norm_imp_below_ds1_looser_strin2stats_potsub$standard_name <- gsub("Tusc5",
                                                                         "Trarg1",
                                                                         phos_gsk3i_raw_norm_imp_below_ds1_looser_strin2stats_potsub$standard_name)
phos_gsk3i_raw_norm_imp_below_ds1_looser_strin2stats_potsub$Gene.names <- gsub("Tusc5",
                                                                         "Trarg1",
                                                                         phos_gsk3i_raw_norm_imp_below_ds1_looser_strin2stats_potsub$Gene.names)
rownames(phos_gsk3i_raw_norm_imp_below_ds1_looser_strin2stats_potsub) <- phos_gsk3i_raw_norm_imp_below_ds1_looser_strin2stats_potsub$standard_name

#Export
save(phos_gsk3i_raw_norm_imp_below_ds1_looser_strin2stats_potsub,
     file = "output/data/phos_gsk3i_raw_norm_imp_below_ds1_looser_strin2stats_potsub__2.RData")
phos_gsk3i_proc <- phos_gsk3i_raw_norm_imp_below_ds1_looser_strin2stats_potsub
save(phos_gsk3i_proc,
     file = "output/data/phos_gsk3i_proc__2.RData")
```

###Export matching motif
```{r}
phos_gsk3i_matches_pST35psp_motif <- phos_gsk3i_raw_norm_imp_below_ds1_looser_strin2stats[, c("standard_name",
                                                                                 "matches_pST35psp_motif")]

save(phos_gsk3i_matches_pST35psp_motif,
     file = "output/data/phos_gsk3i_matches_pST35psp_motif.RData")
```




































































