---
title: "06__pot_sub_and_reg_analysis__3"
output: html_document
---


Background

Here I perform analysis on sites that are pot substrates and regulated



###Initialise

Packages
```{r}
library(ggplot2)
```

###Read in data
```{r}
load("data/intermediate/phos_gsk3i_proc__2.RData")
```

###Big numbers of regulation and pot substrate
```{r}
##Reg
#ppeptides: 790, 309 up, 481 down
#psites: 713, 305 up, 458 down
#pproteins: 395, 230 up, 249 down

length(which(phos_gsk3i_proc$GSK3i_up == TRUE |
               phos_gsk3i_proc$GSK3i_down == TRUE))
length(which(phos_gsk3i_proc$GSK3i_up == TRUE))
length(which(phos_gsk3i_proc$GSK3i_down == TRUE))


length(unique(phos_gsk3i_proc$uniprot_site[which(phos_gsk3i_proc$GSK3i_up == TRUE |
               phos_gsk3i_proc$GSK3i_down == TRUE)]))
length(unique(phos_gsk3i_proc$uniprot_site[which(phos_gsk3i_proc$GSK3i_up == TRUE)]))
length(unique(phos_gsk3i_proc$uniprot_site[which(phos_gsk3i_proc$GSK3i_down == TRUE)]))



length(unique(phos_gsk3i_proc$uniprot[which(phos_gsk3i_proc$GSK3i_up == TRUE |
               phos_gsk3i_proc$GSK3i_down == TRUE)]))
length(unique(phos_gsk3i_proc$uniprot[which(phos_gsk3i_proc$GSK3i_up == TRUE)]))
length(unique(phos_gsk3i_proc$uniprot[which(phos_gsk3i_proc$GSK3i_down == TRUE)]))

```


###Volcano plots
```{r}
###Function: Volcano plot given pval and FC columns (can be adj_pval, and/or rval)
#Up to date 20210221
#Colours significant (pval and FC) proteins
volcano_plot_coloured <- function(data,
                         pval_col,
                         FC_col,
                         pval_cutoff = 0.05,
                         FC_cutoff = 0.58,
                         inner_alpha_val = 0.3,
                         outer_alpha_val = 0.5,
                         size = 1,
                         sig_colour = "red",
                         x_lim = "max",
                         y_lim = "max",
                         remove_Inf = TRUE,
                         return_df = FALSE){

##Set up data
plot_data <- data[, c(FC_col,
                      pval_col)]
colnames(plot_data) <- c("FC",
                         "pval")
plot_data$nlog_pval <- -log10(plot_data$pval)
plot_data$sig <- FALSE
plot_data$sig[which(abs(plot_data$FC) > FC_cutoff &
                      plot_data$pval < pval_cutoff)] <- TRUE


##Remove Inf if desired
if (remove_Inf){
  
  plot_data <- plot_data[which(plot_data$nlog_pval !=
                                 Inf), ]
}

##Get x_lim and y_lim if using max
if (x_lim == "max"){
  
  x_lim <- max(abs(plot_data$FC[which(is.na(plot_data$pval) == FALSE)]),
              na.rm = TRUE)
}  

if (y_lim == "max"){
  
  y_lim <- max(plot_data$nlog_pval[which(plot_data$nlog_pval != Inf)])
}

##Order df by sig
plot_data <- plot_data[order(plot_data$sig), ]




##Output

#return_df
if (return_df){
  
  return(plot_data)
} else {
output_plot <- ggplot(data = plot_data,
       aes(x = FC,
           y = nlog_pval,
           colour = sig,
           fill = sig))+
  geom_point(size = size,
             shape = 21,
             stroke = size*0.3) +
  scale_colour_manual(values = alpha(c("black",
                                 sig_colour),
                                 outer_alpha_val)) +
  scale_fill_manual(values = alpha(c("black",
                                     sig_colour),
                                   alpha = inner_alpha_val)) +
  theme(panel.background = element_blank(),
        panel.grid = element_blank(),
        axis.line = element_line(colour = "black"),
        legend.position = "none",
        plot.title = element_text(hjust = 0.5)) +
  xlim(-x_lim, x_lim) +
  ylim(0, y_lim)
return(output_plot)
}
}

###Volcano plots
#Colour for sig, and downreg + motif

##Get df and manipulate
GSK3i_volcano_df <- volcano_plot_coloured(data = phos_gsk3i_proc,
                      pval_col = "adj_p_val",
                      FC_col = "FC",
                      x_lim = 10,
                      return_df = TRUE)

##Make labels
#site_label_master: greatest degree of granulation
GSK3i_volcano_df$site_label_master <- "Unregulated"
GSK3i_volcano_df$site_label_master[which(GSK3i_volcano_df$sig == TRUE &
                                    GSK3i_volcano_df$FC > 0.58)] <- "Up-regulated"
GSK3i_volcano_df$site_label_master[which(GSK3i_volcano_df$sig == TRUE &
                                    GSK3i_volcano_df$FC < -0.58)] <- "Down-regulated"
GSK3i_volcano_df$site_label_master[which(GSK3i_volcano_df$sig == TRUE &
                                    rownames(GSK3i_volcano_df) %in%
                                    rownames(phos_gsk3i_proc[which(phos_gsk3i_proc$GSK3i_down_motif == TRUE), ]))] <- "Putative substrate"
#site_label_reg: Unregulated vs Regulated
GSK3i_volcano_df$site_label_reg <- GSK3i_volcano_df$site_label_master
GSK3i_volcano_df$site_label_reg[which(GSK3i_volcano_df$site_label_master %in% 
                                        c("Up-regulated",
                                          "Down-regulated",
                                          "Putative substrate"))] <- "Regulated"
#site_label_putsub: 
GSK3i_volcano_df$site_label_putsub <- GSK3i_volcano_df$site_label_master
GSK3i_volcano_df$site_label_putsub[which(GSK3i_volcano_df$site_label_master %in% 
                                        c("Unregulated",
                                          "Up-regulated",
                                          "Down-regulated"))] <- "Not substrate"

#Turn into factors
GSK3i_volcano_df$site_label_master <- factor(GSK3i_volcano_df$site_label_master,
                                      levels = c("Unregulated",
                                                 "Up-regulated",
                                                 "Down-regulated",
                                                 "Putative substrate"))
GSK3i_volcano_df$site_label_reg <- factor(GSK3i_volcano_df$site_label_reg,
                                      levels = c("Unregulated",
                                                 "Regulated"))
GSK3i_volcano_df$site_label_putsub <- factor(GSK3i_volcano_df$site_label_putsub,
                                      levels = c("Not substrate",
                                                 "Putative substrate"))

##Set x_lim, y_lim, and alpha_val
y_lim <- max(GSK3i_volcano_df$nlog_pval,
             na.rm = TRUE)

##Reorder df to optimise plot
GSK3i_volcano_df <- GSK3i_volcano_df[order(GSK3i_volcano_df$site_label_master), ]


##Add labels for geom_label_repel()
GSK3i_volcano_df$gene_site_label <- sapply(rownames(GSK3i_volcano_df),
                                           function(x) paste(strsplit(x,
                                                                      "_")[[1]][c(1, 3)],
                                                             collapse = " "))
GSK3i_volcano_df$gene_site_mult_label <- sapply(rownames(GSK3i_volcano_df),
                                           function(x){
                                             
                                             split_x <- strsplit(x, "_")[[1]]
                                             return(paste(c(split_x[1],
                                                            " ",
                                                            split_x[3],
                                                            " P",
                                                            split_x[4]),
                                                          collapse = ""))
                                           })
GSK3i_volcano_df$gene_site_label_select_GSK3_subs <- GSK3i_volcano_df$gene_site_label
GSK3i_volcano_df$gene_site_label_select_GSK3_subs[which(rownames(GSK3i_volcano_df) %in%
                                                          c("Gys1_Q9Z1E4_S641_3",
                                                              "Gys1_Q9Z1E4_S645_3",
                                                              "Gys1_Q9Z1E4_S649_3") == FALSE)] <- ""



##Plot

#label_master
ggplot(data = GSK3i_volcano_df,
       aes(x = FC,
           y = nlog_pval,
           colour = site_label_master,
           fill = site_label_master)) +
    geom_point(shape = 21,
             size = 1.5,
             stroke = 0.3*1.5) +
  scale_colour_manual(values = alpha(c("#ACACAC",
                                 "#F37970",
                                 "#1FBDC0",
                                 "#3660A5"),
                                 0.5),
                      name = "Site group") +
  scale_fill_manual(values = alpha(c("#ACACAC",
                                 "#F37970",
                                 "#1FBDC0",
                                 "#3660A5"),
                                 0.3),
                      name = "Site group") +
  theme(panel.background = element_blank(),
        panel.grid = element_blank(),
        axis.line = element_line(colour = "black"),
        plot.title = element_text(hjust = 0.5),
        axis.text = element_text(colour = "black")) +
  xlim(-8, 8) +
  ylim(0, y_lim) +
  labs(x = "log2 GSK3i/BASAL",
       y = "-log10 adj. p-val") +
  ggtitle("GSK3i-regulated Phosphopeptides") 
  ggsave("output/images/analysis/volcano_plots/GSK3i_volcanoplot_all_labels.pdf",
         width = 4,
         height = 3)

#label_reg
ggplot(data = GSK3i_volcano_df,
       aes(x = FC,
           y = nlog_pval,
           colour = site_label_reg,
           fill = site_label_reg)) +
    geom_point(shape = 21,
             size = 1.5,
             stroke = 0.3*1.5) +
  scale_colour_manual(values = alpha(c("#ACACAC",
                                 "black"),
                                 0.5),
                      name = "Site group",
                      labels = c("a",
                                 "b")) +
  scale_fill_manual(values = alpha(c("#ACACAC",
                                 "black"),
                                 0.3),
                      name = "Site group",
                    labels = c("a",
                               "b")) +
  theme(panel.background = element_blank(),
        panel.grid = element_blank(),
        axis.line = element_line(colour = "black"),
        plot.title = element_text(hjust = 0.5),
        axis.text = element_text(colour = "black")) +
  xlim(-8, 8) +
  ylim(0, y_lim)+
  labs(x = "log2 GSK3i/BASAL",
       y = "-log10 adj. p-val") +
  ggtitle("GSK3i-regulated Phosphopeptides") 
  ggsave("output/images/analysis/volcano_plots/GSK3i_volcanoplot_reg.pdf",
         width = 3.5,
         height = 3)

#label_putsub
ggplot(data = GSK3i_volcano_df,
       aes(x = FC,
           y = nlog_pval,
           colour = site_label_putsub,
           fill = site_label_putsub)) +
    geom_point(shape = 21,
             size = 1.5,
             stroke = 0.3*1.5) +
  scale_colour_manual(values = alpha(c("#ACACAC",
                                 "#3660A5"),
                                 0.5),
                      name = "Site group",
                      labels = c("a",
                                 "b")) +
  scale_fill_manual(values = alpha(c("#ACACAC",
                                 "#3660A5"),
                                 0.3),
                      name = "Site group",
                    labels = c("a",
                               "b")) +
  theme(panel.background = element_blank(),
        panel.grid = element_blank(),
        axis.line = element_line(colour = "black"),
        plot.title = element_text(hjust = 0.5),
        axis.text = element_text(colour = "black")) +
  xlim(-8, 8)+
  labs(x = "log2 GSK3i/BASAL",
       y = "-log10 adj. p-val") +
  ylim(0, y_lim) +
  ggtitle("GSK3i-regulated Phosphopeptides") 
  ggsave("output/images/analysis/volcano_plots/GSK3i_volcanoplot_putsub.pdf",
         width = 3.5,
         height = 3)


###Cartoon volcano plot for schematic
GSK3i_volcano_df_cartoon <- GSK3i_volcano_df
GSK3i_volcano_df_cartoon <- GSK3i_volcano_df_cartoon[with(GSK3i_volcano_df_cartoon,
                                                          which(nlog_pval < 4.5)), ]
GSK3i_volcano_df_cartoon <- GSK3i_volcano_df_cartoon[-with(GSK3i_volcano_df_cartoon,
                                                           which(abs(FC) > 4 &
                                                                   nlog_pval < 1)), ]

ggplot(data = GSK3i_volcano_df_cartoon,
       aes(x = FC,
           y = nlog_pval,
           colour = site_label_master,
           fill = site_label_master)) +
    geom_point(size = 3) +
  scale_colour_manual(values = alpha(c("#ACACAC",
                                       "#ACACAC",
                                 "#3660A5",
                                 "#3660A5"),
                                 0.5),
                      name = "Site group",
                      labels = c("a",
                                 "b",
                                 "c",
                                 "d")) +
  scale_fill_manual(values = alpha(c("#ACACAC",
                                       "#ACACAC",
                                 "#3660A5",
                                 "#3660A5"),
                                 0.5),
                      name = "Site group",
                      labels = c("a",
                                 "b",
                                 "c",
                                 "d"))  +
  theme(panel.background = element_blank(),
        panel.grid = element_blank(),
        axis.line = element_line(colour = "black"),
        plot.title = element_text(hjust = 0.5),
        axis.text = element_text(colour = "black")) +
  xlim(-8, 8)+
  labs(x = "log2 GSK3i/BASAL",
       y = "-log10 adj. p-val") +
  ylim(0, 4.5) +
  ggtitle("GSK3i-regulated Phosphopeptides") 
  ggsave("output/images/analysis/volcano_plots/GSK3i_volcanoplot_putsub_cartoon.pdf",
         width = 3.5,
         height = 3)
```























